//package com.popble;
//
//import java.time.LocalDate;
//import java.util.ArrayList;
//import java.util.List;
//
//import org.junit.jupiter.api.Test;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.boot.test.context.SpringBootTest;
//
//import com.popble.domain.PopupStore;
//import com.popble.repository.PopupStoreRepository;
//
//@SpringBootTest
//public class PopupStoreDummyDataTests {
//
//	@Autowired
//	PopupStoreRepository popupStoreRepository;
//	
//	@Test
//	public void popupStoreDummy() {
//		
//		List<PopupStore> stores = new ArrayList<>();
//		//1
//        stores.add(PopupStore.builder()
//                .storeName("더현대 서울")
//                .desc("더현대 서울 지하 1층 팝업스토어")
//                .address("서울특별시 영등포구 여의대로 108")
//                .startDate(LocalDate.of(2025, 9, 1))
//                .endDate(LocalDate.of(2025, 9, 30))
//                .price(10000)
//                .status(PopupStore.Status.ACTIVE)
//                .view(500)
//                .recommend(25)
//                .maxCount(1)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(10)
//                .build());
//        //2
//        stores.add(PopupStore.builder()
//                .storeName("성수동 S-Factory")
//                .desc("트렌디한 브랜드의 팝업 성지")
//                .address("서울특별시 성동구 연무장15길 11")
//                .startDate(LocalDate.of(2025, 10, 5))
//                .endDate(LocalDate.of(2025, 10, 20))
//                .price(12000)
//                .status(PopupStore.Status.SCHEDULED)
//                .view(120)
//                .recommend(10)
//                .maxCount(4)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(11)
//                .build());
//        //3
//        stores.add(PopupStore.builder()
//                .storeName("롯데백화점 본점")
//                .desc("브랜드 신제품 런칭 팝업")
//                .address("서울특별시 중구 남대문로 81")
//                .startDate(LocalDate.of(2025, 8, 15))
//                .endDate(LocalDate.of(2025, 8, 30))
//                .price(8000)
//                .status(PopupStore.Status.ENDED)
//                .view(800)
//                .recommend(40)
//                .maxCount(6)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(12)
//                .build());
//        //4
//        stores.add(PopupStore.builder()
//                .storeName("가로수길 팝업")
//                .desc("패션 브랜드 팝업")
//                .address("서울특별시 강남구 가로수길 55")
//                .startDate(LocalDate.of(2025, 9, 10))
//                .endDate(LocalDate.of(2025, 9, 25))
//                .price(9500)
//                .status(PopupStore.Status.ACTIVE)
//                .view(350)
//                .recommend(18)
//                .maxCount(9)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(15)
//                .build());
//        //5
//        stores.add(PopupStore.builder()
//                .storeName("한남동 D-Museum")
//                .desc("전시 연계 팝업스토어")
//                .address("서울특별시 용산구 독서당로29길 5")
//                .startDate(LocalDate.of(2025, 9, 20))
//                .endDate(LocalDate.of(2025, 10, 10))
//                .price(15000)
//                .status(PopupStore.Status.SCHEDULED)
//                .view(200)
//                .recommend(15)
//                .maxCount(5)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(1)
//                .build());
//        //6
//        stores.add(PopupStore.builder()
//                .storeName("코엑스 팝업")
//                .desc("대규모 페스티벌 팝업")
//                .address("서울특별시 강남구 영동대로 513")
//                .startDate(LocalDate.of(2025, 7, 1))
//                .endDate(LocalDate.of(2025, 7, 31))
//                .price(7000)
//                .status(PopupStore.Status.ENDED)
//                .view(1000)
//                .recommend(60)
//                .maxCount(4)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(3)
//                .build());
//        //7
//        stores.add(PopupStore.builder()
//                .storeName("명동 신세계백화점")
//                .desc("뷰티 브랜드 팝업")
//                .address("서울특별시 중구 소공로 63")
//                .startDate(LocalDate.of(2025, 9, 5))
//                .endDate(LocalDate.of(2025, 9, 18))
//                .price(11000)
//                .status(PopupStore.Status.ACTIVE)
//                .view(420)
//                .recommend(22)
//                .maxCount(3)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(5)
//                .build());
//        //8
//        stores.add(PopupStore.builder()
//                .storeName("여의도 IFC몰")
//                .desc("라이프스타일 팝업")
//                .address("서울특별시 영등포구 국제금융로 10")
//                .startDate(LocalDate.of(2025, 10, 1))
//                .endDate(LocalDate.of(2025, 10, 31))
//                .price(9000)
//                .status(PopupStore.Status.SCHEDULED)
//                .view(90)
//                .recommend(5)
//                .maxCount(2)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(3)
//                .build());
//        //9
//        stores.add(PopupStore.builder()
//                .storeName("잠실 롯데월드몰")
//                .desc("캐릭터 팝업스토어")
//                .address("서울특별시 송파구 올림픽로 300")
//                .startDate(LocalDate.of(2025, 8, 1))
//                .endDate(LocalDate.of(2025, 8, 20))
//                .price(13000)
//                .status(PopupStore.Status.ENDED)
//                .view(650)
//                .recommend(30)
//                .maxCount(1)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(2)
//                .build());
//        //10
//        stores.add(PopupStore.builder()
//                .storeName("홍대 AK&")
//                .desc("인디 브랜드 팝업")
//                .address("서울특별시 마포구 양화로 188")
//                .startDate(LocalDate.of(2025, 9, 15))
//                .endDate(LocalDate.of(2025, 9, 30))
//                .price(10500)
//                .status(PopupStore.Status.ACTIVE)
//                .view(300)
//                .recommend(16)
//                .maxCount(10)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(5)
//                .build());
//        //11
//        stores.add(PopupStore.builder()
//                .storeName("부산 센텀시티 신세계백화점")
//                .desc("해운대구의 랜드마크 팝업")
//                .address("부산광역시 해운대구 센텀남대로 35")
//                .startDate(LocalDate.of(2025, 10, 10))
//                .endDate(LocalDate.of(2025, 10, 25))
//                .price(14000)
//                .status(PopupStore.Status.SCHEDULED)
//                .view(150)
//                .recommend(8)
//                .maxCount(5)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(4)
//                .build());
//        //12
//        stores.add(PopupStore.builder()
//                .storeName("광주 유스퀘어")
//                .desc("광주광역시 문화복합공간 팝업")
//                .address("광주광역시 서구 무진대로 904")
//                .startDate(LocalDate.of(2025, 9, 1))
//                .endDate(LocalDate.of(2025, 9, 14))
//                .price(8500)
//                .status(PopupStore.Status.ACTIVE)
//                .view(250)
//                .recommend(12)
//                .maxCount(2)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(7)
//                .build());
//        //13
//        stores.add(PopupStore.builder()
//                .storeName("대전 신세계백화점 아트앤사이언스")
//                .desc("과학과 예술이 만나는 팝업")
//                .address("대전광역시 유성구 엑스포로 1")
//                .startDate(LocalDate.of(2025, 8, 20))
//                .endDate(LocalDate.of(2025, 9, 5))
//                .price(9800)
//                .status(PopupStore.Status.ENDED)
//                .view(550)
//                .recommend(35)
//                .maxCount(7)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(9)
//                .build());
//        //14
//        stores.add(PopupStore.builder()
//                .storeName("인천 송도 현대프리미엄아울렛")
//                .desc("송도국제도시의 쇼핑 팝업")
//                .address("인천광역시 연수구 송도국제대로 123")
//                .startDate(LocalDate.of(2025, 9, 22))
//                .endDate(LocalDate.of(2025, 10, 7))
//                .price(11500)
//                .status(PopupStore.Status.ACTIVE)
//                .view(380)
//                .recommend(20)
//                .maxCount(6)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(13)
//                .build());
//        //15
//        stores.add(PopupStore.builder()
//                .storeName("제주 신화월드")
//                .desc("제주도 힐링 테마 팝업")
//                .address("제주특별자치도 서귀포시 안덕면 신화역사로304번길 38")
//                .startDate(LocalDate.of(2025, 10, 15))
//                .endDate(LocalDate.of(2025, 11, 15))
//                .price(18000)
//                .status(PopupStore.Status.SCHEDULED)
//                .view(70)
//                .recommend(3)
//                .maxCount(1)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(6)
//                .build());
//        //16
//        stores.add(PopupStore.builder()
//                .storeName("대구 동성로")
//                .desc("대구 최대 번화가 팝업")
//                .address("대구광역시 중구 동성로3길 100")
//                .startDate(LocalDate.of(2025, 8, 5))
//                .endDate(LocalDate.of(2025, 8, 25))
//                .price(7500)
//                .status(PopupStore.Status.ENDED)
//                .view(950)
//                .recommend(50)
//                .maxCount(3)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(10)
//                .build());
//        //17
//        stores.add(PopupStore.builder()
//                .storeName("수원 AK플라자")
//                .desc("수원역 인근 대형 팝업")
//                .address("경기도 수원시 팔달구 덕영대로 924")
//                .startDate(LocalDate.of(2025, 9, 8))
//                .endDate(LocalDate.of(2025, 9, 21))
//                .price(10000)
//                .status(PopupStore.Status.ACTIVE)
//                .view(400)
//                .recommend(25)
//                .maxCount(4)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(8)
//                .build());
//        //18
//        stores.add(PopupStore.builder()
//                .storeName("전주 한옥마을")
//                .desc("전통과 현대의 조화 팝업")
//                .address("전라북도 전주시 완산구 기린대로 99")
//                .startDate(LocalDate.of(2025, 10, 1))
//                .endDate(LocalDate.of(2025, 10, 20))
//                .price(9000)
//                .status(PopupStore.Status.SCHEDULED)
//                .view(180)
//                .recommend(11)
//                .maxCount(2)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(14)
//                .build());
//        //19
//        stores.add(PopupStore.builder()
//                .storeName("강원도 속초 롯데리조트")
//                .desc("속초 해변 뷰 팝업")
//                .address("강원특별자치도 속초시 동해대로 3672")
//                .startDate(LocalDate.of(2025, 7, 10))
//                .endDate(LocalDate.of(2025, 7, 30))
//                .price(12500)
//                .status(PopupStore.Status.ENDED)
//                .view(750)
//                .recommend(45)
//                .maxCount(5)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(16)
//                .build());
//        //20
//        stores.add(PopupStore.builder()
//                .storeName("청주 현대백화점")
//                .desc("충청권 대표 팝업")
//                .address("충청북도 청주시 흥덕구 직지대로 308")
//                .startDate(LocalDate.of(2025, 9, 25))
//                .endDate(LocalDate.of(2025, 10, 5))
//                .price(11000)
//                .status(PopupStore.Status.ACTIVE)
//                .view(320)
//                .recommend(17)
//                .maxCount(8)
//                .deleted(false)
//                .categories(new ArrayList<>())
//                .reservations(new ArrayList<>())
//                .reservationTimes(new ArrayList<>())
//                .bookmarkCount(11)
//                .build());
//        
//        popupStoreRepository.saveAll(stores);
//		
//	}
//}
